export const PrivateRoutes = {
	HOME: 'home',
	CRYPTO: 'crypto',
	STOCKS: 'stocks',
	BANK: 'bank',
	MAIN: 'main',
};

export const PrivatePaths: Record<keyof typeof PrivateRoutes, string> = {
	HOME: '/home',
	CRYPTO: '/crypto',
	STOCKS: '/stocks',
	BANK: '/bank',
	MAIN: '/main',
};

export const PRIVATE_NAVIGATION_ITEMS = [
	{
		id: 'main',
		path: PrivatePaths.MAIN,
		label: 'Overview',
		description: 'Open your main dashboard overview.',
		category: 'Pages',
		keywords: ['main', 'dashboard', 'overview', 'home', 'summary'],
		icon: 'main',
	},
	{
		id: 'crypto',
		path: PrivatePaths.CRYPTO,
		label: 'Crypto',
		description: 'Review crypto accounts and transactions.',
		category: 'Pages',
		keywords: ['crypto', 'wallets', 'coins', 'btc', 'ethereum'],
		icon: 'crypto',
	},
	{
		id: 'stocks',
		path: PrivatePaths.STOCKS,
		label: 'Stocks',
		description: 'Track brokerage balances and stock activity.',
		category: 'Pages',
		keywords: ['stocks', 'equities', 'shares', 'portfolio'],
		icon: 'stocks',
	},
	{
		id: 'bank',
		path: PrivatePaths.BANK,
		label: 'Bank',
		description: 'Monitor bank accounts and cash flow.',
		category: 'Pages',
		keywords: ['bank', 'banking', 'cash', 'cards', 'accounts'],
		icon: 'bank',
	},
	{
		id: 'new-transaction',
		path: PrivatePaths.MAIN,
		label: 'New transaction',
		description: 'Go to a dashboard page and create a new transaction.',
		category: 'Actions',
		keywords: ['new transaction', 'create transaction', 'income', 'expense'],
		icon: 'transaction',
	},
	{
		id: 'analytics',
		path: PrivatePaths.MAIN,
		label: 'Analytics',
		description: 'Open charts and portfolio analytics.',
		category: 'Shortcuts',
		keywords: ['analytics', 'charts', 'pie chart', 'line chart', 'reports'],
		icon: 'analytics',
	},
	{
		id: 'quick-navigation',
		path: PrivatePaths.MAIN,
		label: 'Keyboard navigation',
		description: 'Use the top search to jump between sections quickly.',
		category: 'Shortcuts',
		keywords: ['keyboard', 'shortcut', 'search', 'jump'],
		icon: 'shortcut',
	},
] as const;
